/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Example */

#ifndef _Included_Example
#define _Included_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Example
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Example_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
