/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_hsr_ifs_liquids_devices_Accelerometer */

#ifndef _Included_ch_hsr_ifs_liquids_devices_Accelerometer
#define _Included_ch_hsr_ifs_liquids_devices_Accelerometer
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_hsr_ifs_liquids_devices_Accelerometer_STEP
#define ch_hsr_ifs_liquids_devices_Accelerometer_STEP 1.0f
#undef ch_hsr_ifs_liquids_devices_Accelerometer_PRECISION
#define ch_hsr_ifs_liquids_devices_Accelerometer_PRECISION 6.0f
/*
 * Class:     ch_hsr_ifs_liquids_devices_Accelerometer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_hsr_ifs_liquids_devices_Accelerometer_init
  (JNIEnv *, jclass);

/*
 * Class:     ch_hsr_ifs_liquids_devices_Accelerometer
 * Method:    remove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_hsr_ifs_liquids_devices_Accelerometer_remove
  (JNIEnv *, jclass);

/*
 * Class:     ch_hsr_ifs_liquids_devices_Accelerometer
 * Method:    readAcceleration
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_ch_hsr_ifs_liquids_devices_Accelerometer_readAcceleration
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
